# Generated by Django 5.2.9 on 2025-12-06 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='BigExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.FloatField()),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='big_info', to='expenses.expense')),
            ],
        ),
    ]
