# Generated by Django 5.2.9 on 2025-12-07 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_name_bigexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='big_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bigexpense',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='big_expenses', to='expenses.expense'),
        ),
    ]
